import asyncio, subprocess, time, json
from playwright.async_api import async_playwright
exec(open('/home/claude/outil/test16.py').read().split('async def main')[0])
async def main():
    srv = subprocess.Popen(['python3', '-m', 'http.server', '8795', '--bind', '127.0.0.1'], cwd=SITE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL); time.sleep(1)
    try:
        async with async_playwright() as p:
            b = await p.chromium.launch(args=['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', '--use-file-for-fake-audio-capture=' + FAKE])
            ctx = await b.new_context(viewport={'width': 1440, 'height': 900}); await ctx.add_init_script(INIT); await ctx.grant_permissions(['microphone'], origin='http://127.0.0.1:8795')
            page = await ctx.new_page(); errs = []; page.on('pageerror', lambda e: errs.append(str(e))); ev = page.evaluate
            await page.goto('http://127.0.0.1:8795/'); await page.wait_for_timeout(1200); await ev('window.S=__atelier.S; window.prefs=__atelier.prefs; 1')
            await page.set_input_files('#fileInput', COURS); await page.wait_for_timeout(1500)
            await page.click('#recBtn'); await page.wait_for_selector('#rqKeep')
            await page.click('#rqKeep [data-v="0"]'); await page.screenshot(path=OUT + '/8-texte-seul.png')
            await page.click('#rqGo'); await page.wait_for_timeout(1500)
            ok('réglage « Seulement le texte » enregistré', await ev('prefs.recKeepAudio === false && Rec.r.noAudio === true'))
            await page.wait_for_timeout(4000)
            await page.click('#quick'); await page.keyboard.type('Note sans son'); await page.keyboard.press('Enter'); await page.wait_for_timeout(300); await page.keyboard.press('Escape')
            await wait_for(ev, 'Rec.samples/16000 > 32', 60)
            ch = await ev('AStore.keys("chunks", Rec.r.id + "/").then(k => k.length)')
            ok('aucun fichier son enregistré pendant le cours', ch == 0 and await ev('Rec.r.parts.length === 0'), ch)
            await ev('Rec.stop()'); await page.wait_for_timeout(1500)
            done = await wait_for(ev, 'TQ.list.length === 0 && !TQ.running', 240)
            r = await ev('(async () => { const r = S.doc.recs[0]; return { segs: r.segs.length, jobs: (await AStore.keys("jobs")).length, chunks: (await AStore.keys("chunks")).length }; })()')
            ok('transcription faite, son temporaire effacé', done and r['segs'] > 0 and r['jobs'] == 0 and r['chunks'] == 0, r)
            await page.click('#tabPage'); await page.wait_for_timeout(400)
            ok('bouton ≡ sur la note (pas de ▶)', await ev('!!document.querySelector(".note .recb.txt") && document.querySelector(".note .recb").textContent.startsWith("≡")'))
            await ev('document.querySelector(".note .recb").click()'); await page.wait_for_timeout(800)
            ok('≡ ouvre la transcription au bon passage', await ev('S.view === "trans" && !!document.querySelector(".tseg.playing") && document.getElementById("pbar").classList.contains("hidden")'))
            await page.click('.tr-more'); await page.wait_for_timeout(200)
            ok('menu sans « Écouter » ni « Télécharger le son »', await ev('!document.querySelector("#ddTr [data-t=play]") && !document.querySelector("#ddTr [data-t=audio]") && !!document.querySelector("#ddTr [data-t=md]")'))
            await page.keyboard.press('Escape')
            await ev('document.querySelector(".tseg .tt").click()'); await page.wait_for_timeout(500)
            ok('clic sur une minute : pas de lecteur', await ev('document.getElementById("pbar").classList.contains("hidden")'))
            await page.set_input_files('#audioInput', WEBM); await page.wait_for_timeout(500)
            done2 = await wait_for(ev, 'S.doc.recs.length === 2 && S.doc.recs[1].segs.length > 0 && TQ.list.length === 0 && !TQ.running', 240)
            c2 = await ev('AStore.keys("chunks").then(k => k.length)')
            ok('fichier audio en mode texte seul : transcrit puis effacé', done2 and c2 == 0 and await ev('S.doc.recs[1].parts.length === 0'), c2)
            md = await ev('ToClaude.build(S.doc, {hl:true, images:false, peers:false, trans:true, since:0}).then(r=>r.md)')
            ok('Envoyer à Claude : transcription incluse', 'Transcription du cours oral' in md)
            ok('aucune erreur JavaScript', not errs, errs[:3])
            await b.close()
    finally: srv.kill()
    print('\nRÉSUMÉ', sum(1 for _, c in R if c), '/', len(R))
asyncio.run(main())
