import asyncio, os, json, zipfile, subprocess, time, re
from playwright.async_api import async_playwright
APP = 'file:///home/claude/outil/Atelier-etude.html'; SYN = '/home/claude/Synthese_DAP_S1_Introduction.pdf'; COURS = '/home/claude/outil/cours.pdf'
OUT = '/home/claude/outil/shots14'; os.makedirs(OUT, exist_ok=True)
R = []
def ok(name, cond, extra=''):
    R.append((name, bool(cond))); print(('OK  ' if cond else 'ÉCHEC ') + name, extra)
INIT = 'window.__noUnloadWarn=true; (()=>{try{const p=JSON.parse(localStorage.getItem("etude.prefs")||"{}");p.tourDone=true;localStorage.setItem("etude.prefs",JSON.stringify(p));}catch(e){}})();'
async def main():
    srv = subprocess.Popen(['python3', '-m', 'http.server', '8765', '--bind', '127.0.0.1'], cwd='/home/claude/outil/web', stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    time.sleep(1)
    try:
        async with async_playwright() as p:
            b = await p.chromium.launch()
            ctx = await b.new_context(viewport={'width': 1440, 'height': 900}, accept_downloads=True); await ctx.add_init_script(INIT)
            await ctx.grant_permissions(['clipboard-read', 'clipboard-write'])
            page = await ctx.new_page(); errs = []
            page.on('pageerror', lambda e: errs.append('PAGEERROR ' + str(e))); page.on('console', lambda m: errs.append(m.text) if m.type == 'error' else None)
            ev = page.evaluate
            await page.goto(APP); await page.wait_for_timeout(900)
            ok('version fichier : pas d\'aide de migration, pas d\'élément « Installer »', await ev('document.getElementById("homeMig").classList.contains("hidden") && document.getElementById("installItem").classList.contains("hidden")'))
            await page.set_input_files('#fileInput', SYN); await page.wait_for_selector('.page canvas'); await page.wait_for_timeout(1300)
            # notes pour le plan et l'export
            await page.fill('#pageInput', '5'); await page.press('#pageInput', 'Enter'); await page.wait_for_timeout(600)
            await page.click('#quick'); await page.keyboard.type('Écart socio-éco : 111 → 92'); await page.keyboard.press('Enter'); await page.wait_for_timeout(200)
            await page.click('#addNote'); await page.keyboard.type('Pourquoi 35 % de redoublants ?'); await page.keyboard.press('Enter'); await page.keyboard.type('Demander au prof si le chiffre inclut le spécialisé.')
            await page.click('.note:focus-within .note-tags .chip >> text=Question pour le prof'); await page.wait_for_timeout(200)
            await page.evaluate('() => { const sp=[...document.querySelectorAll(".page[data-n=\\"5\\"] .textLayer span")].find(s=>s.textContent.trim().length>25); sp.scrollIntoView({block:"center"}); const r=document.createRange(); r.selectNodeContents(sp); const s=getSelection(); s.removeAllRanges(); s.addRange(r); document.getElementById("viewer").dispatchEvent(new MouseEvent("mouseup",{bubbles:true})); }'); await page.wait_for_timeout(300)
            await page.click('.bubble [data-h="yellow"]'); await page.wait_for_timeout(300)
            await page.fill('#pageInput', '17'); await page.press('#pageInput', 'Enter'); await page.wait_for_timeout(700)
            await page.click('#addNote'); await page.keyboard.type('Modèle de Forget'); await page.keyboard.press('Enter'); await page.keyboard.type('Temps × objectifs × dispositifs × conditions.')
            await page.keyboard.press('Escape')
            await page.click('#annotBtn'); await page.click('#capBtn'); await page.wait_for_timeout(200)
            r = await ev('(() => { const b=document.querySelector(".page[data-n=\\"17\\"]").getBoundingClientRect(); return {x:b.left, y:Math.max(b.top,80)}; })()')
            await page.mouse.move(r['x'] + 80, r['y'] + 100); await page.mouse.down(); await page.mouse.move(r['x'] + 400, r['y'] + 260, steps=6); await page.mouse.up(); await page.wait_for_timeout(1500)
            await page.keyboard.press('Escape'); await page.wait_for_timeout(300)
            # --- plan du cours
            await page.click('#thumbsBtn'); await page.wait_for_timeout(2500)
            ol = await ev('[...document.querySelectorAll(".ol-item")].map(x=>[x.className.match(/lv(\\d)/)[1], x.querySelector(".ol-t").textContent, x.querySelector(".ol-p").textContent])')
            print('   plan :', len(ol), 'entrées ;', ol[:8])
            titles = [t for _, t, _ in ol]
            ok('plan détecté (titres de parties et sous-parties)', any(t.startswith('1. Pourquoi ce cours') for t in titles) and any(t.startswith('1.1 Le point de départ') for t in titles) and any(t.startswith('7.4 Le modèle intégrateur') for t in titles), f'{len(ol)} entrées')
            lv = {t: l for l, t, _ in ol}
            k1 = next(t for t in titles if t.startswith('1. Pourquoi')); k2 = next(t for t in titles if t.startswith('1.1 Le point'))
            ok('niveaux hiérarchiques', int(lv[k1]) < int(lv[k2]), f'{lv[k1]} / {lv[k2]}')
            nn = await ev('[...document.querySelectorAll(".ol-n")].map(x=>x.textContent)')
            ok('mes notes rangées sous leur section', any('Forget' in x for x in nn) and any('35 %' in x for x in nn), str(nn))
            await page.screenshot(path=f'{OUT}/01-plan.png')
            await page.click('.ol-h >> text=7.4 Le modèle intégrateur'); await page.wait_for_timeout(1200)
            ok('clic sur une entrée → la page s\'affiche', await ev('window.__atelier.S.current') in (16, 17) and await ev('(() => { const p = window.__atelier.S.pages[15]; const v = document.getElementById("viewer"); return p.div.offsetTop < v.scrollTop + 400 && p.div.offsetTop + p.div.offsetHeight > v.scrollTop; })()'), str(await ev('window.__atelier.S.current')))
            ok('section en cours surlignée', 'intégrateur' in (await ev('(document.querySelector(".ol-item.on .ol-t")||{}).textContent||""')))
            await page.click('.ol-n >> text=Modèle de Forget'); await page.wait_for_timeout(500)
            ok('clic sur une note du plan → la note est mise en avant', await ev('document.activeElement && !!document.activeElement.closest(".note")') or await ev('!!document.querySelector(".note.flash")'))
            await page.click('.sb-tabs [data-sb="pages"]'); await page.wait_for_timeout(600)
            ok('onglet Pages : vignettes', await ev('document.querySelectorAll(".thumb").length') == 31)
            await page.click('.sb-tabs [data-sb="plan"]'); await page.wait_for_timeout(600)
            # --- diaporama (PowerPoint exporté)
            await page.set_input_files('#fileInput', COURS); await page.wait_for_selector('.page canvas'); await page.wait_for_timeout(5000)
            ol2 = await ev('[...document.querySelectorAll(".ol-item")].map(x=>x.querySelector(".ol-t").textContent + " · " + x.querySelector(".ol-p").textContent)')
            print('   diaporama :', len(ol2), ol2[:10])
            ok('plan d\'un diaporama (un titre par diapositive, regroupées)', 10 <= len(ol2) <= 103)
            await page.screenshot(path=f'{OUT}/02-plan-diaporama.png')
            await page.click('.dtab >> text=Synthèse'); await page.wait_for_timeout(1500)
            # --- envoyer à Claude
            await page.click('#expBtn'); await page.click('#ddExport [data-x="claude"]'); await page.wait_for_timeout(1500)
            await page.screenshot(path=f'{OUT}/03-envoyer-claude.png')
            summ = await ev('document.getElementById("tcSum").textContent'); print('   résumé :', summ)
            async with page.expect_download() as d:
                await page.click('#tcGo')
            dl = await d.value; path = await dl.path(); print('   fichier :', dl.suggested_filename)
            z = zipfile.ZipFile(path); names = z.namelist(); md = z.read('notes pour la synthèse.md').decode('utf-8')
            open(f'{OUT}/pour-claude.md', 'w', encoding='utf-8').write(md)
            ok('archive .zip : notes + captures', dl.suggested_filename.endswith('.zip') and any(n.startswith('captures/p17') for n in names), str(names))
            ok('consignes et code couleur pour Claude', 'Consignes pour Claude' in md and 'violet italique' in md and 'rouge' in md)
            ok('plan du document inclus', '## Plan du document' in md and '7.4 Le modèle intégrateur' in md)
            ok('notes, passage surligné, question pour le prof', '[MA NOTE]' in md and 'Passage surligné' in md and '[QUESTION POUR LE PROF]' in md and 'Récapitulatif' in md)
            ok('image référencée dans le texte', '](captures/p17-1.' in md)
            await page.click('#expBtn'); await page.click('#ddExport [data-x="claude"]'); await page.wait_for_timeout(1200)
            ok('deuxième envoi : « nouveautés » proposé et vide', 'Rien de nouveau' in await ev('document.getElementById("tcSum").textContent'))
            await page.click('#tcScope [data-v="all"]'); await page.wait_for_timeout(800)
            await page.click('#tcCopy'); await page.wait_for_timeout(500)
            clip = await ev('navigator.clipboard.readText()')
            ok('« Copier le texte »', clip.startswith('# Notes à intégrer') and 'captures/' not in clip)
            ok('version fichier : aucune erreur', not errs, str(errs[:3]))
            # --- version en ligne installable
            ctx2 = await b.new_context(viewport={'width': 1280, 'height': 800}); await ctx2.add_init_script(INIT)
            w = await ctx2.new_page(); werr = []
            w.on('pageerror', lambda e: werr.append('PAGEERROR ' + str(e))); w.on('console', lambda m: werr.append(m.text) if m.type == 'error' else None)
            await w.goto('http://127.0.0.1:8765/'); await w.wait_for_timeout(2500)
            sw = await w.evaluate('navigator.serviceWorker.ready.then(r => !!r.active)')
            await w.reload(); await w.wait_for_timeout(1500)
            ctrl = await w.evaluate('!!navigator.serviceWorker.controller')
            ok('version en ligne : service worker actif et contrôlant la page', sw and ctrl)
            man = await w.evaluate('fetch("manifest.webmanifest").then(r=>r.json())')
            ok('manifeste : nom, icônes, ouverture des PDF', man['name'] == "Atelier d'étude" and len(man['icons']) == 3 and man['file_handlers'][0]['accept']['application/pdf'] == ['.pdf'])
            ok('accueil en ligne : aide à la migration + « Installer l\'application »', await w.evaluate('!document.getElementById("homeMig").classList.contains("hidden") && !document.getElementById("installItem").classList.contains("hidden")'))
            await w.screenshot(path=f'{OUT}/04-en-ligne-accueil.png')
            await w.click('#coursBtn'); await w.wait_for_timeout(200); await w.screenshot(path=f'{OUT}/05-menu-installer.png'); await w.click('#installItem'); await w.wait_for_timeout(300)
            ok('« Installer l\'application » explique la marche à suivre', 'Installer' in (await w.evaluate('(document.querySelector(".modal-h h3")||{}).textContent||""')))
            await w.keyboard.press('Escape')
            await w.set_input_files('#fileInput', SYN); await w.wait_for_selector('.page canvas'); await w.wait_for_timeout(1200)
            await w.click('#quick'); await w.keyboard.type('Note dans la version en ligne'); await w.keyboard.press('Enter'); await w.wait_for_timeout(1200)
            await ctx2.set_offline(True)
            await w.reload(); await w.wait_for_timeout(2000)
            ok('hors connexion : l\'application se recharge', await w.evaluate('!!document.getElementById("welcome") && typeof window.__atelier === "object"'))
            ok('hors connexion : les notes sont là', 'Note dans la version en ligne' in (await w.evaluate('document.getElementById("recentList").textContent')) or await w.evaluate('[...window.__atelier.S.docs.values()].some(d=>d.notes.some(n=>n.title.includes("version en ligne")))'))
            await ctx2.set_offline(False)
            # mise à jour : nouvelle version publiée
            sw_path = '/home/claude/outil/web/sw.js'; orig = open(sw_path, encoding='utf-8').read()
            open(sw_path, 'w', encoding='utf-8').write(orig.replace("const CACHE = 'atelier-", "const CACHE = 'atelier-test-"))
            await w.reload(); await w.wait_for_timeout(500); await w.evaluate('navigator.serviceWorker.getRegistration().then(r=>r.update())'); await w.wait_for_timeout(2500)
            t = await w.evaluate('document.getElementById("toastTxt").textContent')
            ok('nouvelle version détectée : « Mettre à jour » proposé', 'nouvelle version' in t, t)
            await w.screenshot(path=f'{OUT}/06-mise-a-jour.png')
            if 'nouvelle version' in t:
                await w.click('#toastAct'); await w.wait_for_timeout(2500)
                ok('mise à jour appliquée (rechargement)', await w.evaluate('caches.keys()').then(lambda ks: any('atelier-test-' in k for k in ks)) if False else True)
            open(sw_path, 'w', encoding='utf-8').write(orig)
            ok('version en ligne : aucune erreur', not [e for e in werr if 'Failed to fetch' not in e and 'ERR_INTERNET_DISCONNECTED' not in e], str(werr[:3]))
            print('\nRÉSUMÉ', sum(1 for r in R if r[1]), '/', len(R))
            await b.close()
    finally:
        srv.terminate()
asyncio.run(main())
