import asyncio, subprocess, time, os
from playwright.async_api import async_playwright
SITE = '/home/claude/whisper/site'; COURS = '/home/claude/outil/cours.pdf'; OUT = '/home/claude/outil/shots20'; os.makedirs(OUT, exist_ok=True)
R = []
def ok(name, cond, extra=''):
    R.append((name, bool(cond))); print(('OK  ' if cond else 'ÉCHEC ') + name, extra, flush=True)
INIT = 'window.__noUnloadWarn=true; (()=>{try{const p=JSON.parse(localStorage.getItem("etude.prefs")||"{}");p.tourDone=true;localStorage.setItem("etude.prefs",JSON.stringify(p));}catch(e){}})();'
async def main():
    srv = subprocess.Popen(['python3', '-m', 'http.server', '8798', '--bind', '127.0.0.1'], cwd=SITE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL); time.sleep(1)
    try:
        async with async_playwright() as p:
            b = await p.chromium.launch(); ctx = await b.new_context(viewport={'width': 1440, 'height': 900}); await ctx.add_init_script(INIT)
            page = await ctx.new_page(); errs = []
            page.on('pageerror', lambda e: errs.append('PAGEERROR ' + str(e))); page.on('console', lambda m: errs.append(m.text) if m.type == 'error' and 'favicon' not in m.text else None)
            ev = page.evaluate
            await page.goto('http://127.0.0.1:8798/'); await page.wait_for_timeout(1200); await ev('window.S=__atelier.S; window.prefs=__atelier.prefs; 1')
            await page.click('#nbBtn2'); await page.wait_for_timeout(700)
            ok('carnet créé (mode carnet, panneau d\'accueil)', await ev('document.body.classList.contains("nb") && S.doc.kind === "blank" && !document.getElementById("nbStage").classList.contains("hidden") && document.activeElement.id === "docTitle"'))
            ok('outils PDF masqués, Enregistrer visible', await ev('["thumbsBtn","searchBox","annotBtn","tabPage","quoteBtn"].every(id => !document.getElementById(id).offsetParent) && !!document.getElementById("recBtn").offsetParent'))
            await page.keyboard.type('Séminaire Dupont'); await page.wait_for_timeout(300)
            ok('titre du carnet', await ev('S.doc.title === "Séminaire Dupont"'))
            await page.screenshot(path=OUT + '/1-carnet.png')
            await page.click('#quick'); await page.keyboard.type('Le gvt belge et la crise'); await page.keyboard.press('Enter'); await page.wait_for_timeout(400)
            ok('abréviation dans la note rapide', await ev('S.doc.notes.at(-1).title') == 'Le gouvernement belge et la crise', await ev('S.doc.notes.at(-1).title'))
            await page.click('#addNote'); await page.wait_for_timeout(300)
            await page.keyboard.type('Gvt et pb.'); await page.wait_for_timeout(200)
            ok('abréviation dans un titre, majuscule suivie', await ev('document.activeElement.value') == 'Gouvernement et problème.', await ev('document.activeElement.value'))
            await page.keyboard.press('Enter'); await page.keyboard.type('Le gvt a un pb, GVT bcp '); await page.keyboard.press('Backspace'); await page.wait_for_timeout(300)
            body = await ev('document.querySelector(".note:focus-within .body").textContent')
            ok('abréviations dans le texte, majuscules, ⌫ annule', body.replace(' ', ' ') == 'Le gouvernement a un problème, GOUVERNEMENT bcp ', repr(body))
            await page.keyboard.type('cela'); await page.wait_for_timeout(200)
            ok('on continue à écrire après l\'annulation', (await ev('document.querySelector(".note:focus-within .body").textContent')).replace('\u00a0', ' ').endswith('bcp cela'))
            await page.keyboard.press('Escape'); await page.wait_for_timeout(500)
            ok('note enregistrée avec les mots complets', 'gouvernement a un problème' in await ev('S.doc.notes.at(-1).html'))
            await page.click('#viewBtn'); await page.click('#abbrBtn'); await page.wait_for_selector('#abTxt')
            await page.fill('#abTxt', 'zz = Zanzibar\ngvt = gouvernement'); await page.click('#abOk'); await page.wait_for_timeout(300)
            await page.click('#quick'); await page.keyboard.type('Voyage zz demain'); await page.wait_for_timeout(200)
            ok('liste personnelle', await ev('document.getElementById("quick").value') == 'Voyage Zanzibar demain', await ev('document.getElementById("quick").value'))
            await ev('document.getElementById("quick").value=""'); await ev('prefs.abbrOn = false; 1')
            await page.keyboard.type('le gvt '); ok('désactivable', await ev('document.getElementById("quick").value') == 'le gvt ')
            await ev('document.getElementById("quick").value=""; prefs.abbrOn = true; 1'); await page.keyboard.press('Escape')
            order = await ev('[...document.querySelectorAll(".notes-list .note")].map(x => S.doc.notes.find(n => n.id === x.dataset.id).created)')
            ok('notes dans l\'ordre où elles sont prises', order == sorted(order) and len(order) == 2, order)
            ok('pas de « Page 1 »', await ev('!document.querySelector(".notes-list .page-group h4") && ![...document.querySelectorAll(".note .pbadge")].some(x => x.offsetParent)'))
            md = await ev('ToClaude.build(S.doc, {hl:true, images:true, peers:false, trans:true, since:0}).then(r => r.md)')
            ok('Envoyer à Claude', "Notes dans l'ordre du cours" in md and 'Le gouvernement belge' in md)
            await page.screenshot(path=OUT + '/2-notes.png')
            await page.set_viewport_size({'width': 1280, 'height': 800}); await page.wait_for_timeout(500)
            w = await ev('({sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth})'); ok('1280 px sans débordement', w['sw'] <= w['cw'], w)
            await page.set_viewport_size({'width': 1440, 'height': 900})
            # rattacher à un PDF
            nbfp = await ev('S.doc.fp')
            await ev('Nb.pendingAttach = { fp: S.doc.fp, until: Date.now() + 60000 }; 1')
            await page.set_input_files('#fileInput', COURS); await page.wait_for_selector('.page canvas'); await page.wait_for_timeout(1500)
            st = await ev(f'({{ kind: S.doc.kind || "pdf", n: S.doc.notes.length, pages: [...new Set(S.doc.notes.map(n => n.page))], gone: !S.docs.has("{nbfp}"), tabs: S.tabs.length, nb: document.body.classList.contains("nb"), toast: document.getElementById("toastTxt").textContent }})')
            ok('rattaché au PDF : notes déplacées, carnet retiré', st['kind'] == 'pdf' and st['n'] == 2 and st['pages'] == [1] and st['gone'] and st['tabs'] == 1 and not st['nb'], st)
            # second carnet, fermeture, réouverture
            await page.click('#coursBtn'); await page.click('#nbItem'); await page.wait_for_timeout(600)
            await page.click('#quick'); await page.keyboard.type('Une idée'); await page.keyboard.press('Enter'); await page.wait_for_timeout(300)
            ok('carnet depuis le menu Cours, onglets', await ev('S.doc.kind === "blank" && S.tabs.length === 2'))
            await ev('[...document.querySelectorAll(".dtab")].find(x => x.classList.contains("on")).querySelector(".x").click()'); await page.wait_for_timeout(600)
            ok('fermer le carnet : retour au PDF', await ev('!S.doc.kind && !document.body.classList.contains("nb") && S.pages.length > 0'))
            await ev('[...document.querySelectorAll(".dtab")].forEach(x => x.querySelector(".x").click())'); await page.wait_for_timeout(600)
            await ev('[...document.querySelectorAll("#recentList .lib-item")].find(x => x.textContent.includes("Cours du")).click()'); await page.wait_for_timeout(700)
            ok('rouvert depuis « Reprendre un cours »', await ev('S.doc && S.doc.kind === "blank" && S.doc.notes.length === 1'))
            ok('aucune erreur JavaScript', not errs, errs[:5])
            await b.close()
    finally: srv.kill()
    print('\nRÉSUMÉ', sum(1 for _, c in R if c), '/', len(R))
asyncio.run(main())
