import asyncio, os, json
from playwright.async_api import async_playwright
OLD='file:///home/claude/outil/Atelier-ancien.html'; APP='file:///home/claude/outil/Atelier-etude.html'
SYN='/home/claude/Synthese_DAP_S1_Introduction.pdf'; OUT='/home/claude/outil/shots10'; os.makedirs(OUT, exist_ok=True)
DIRMOCK = open('/home/claude/outil/test6.py', encoding='utf-8').read().split("DIRMOCK = '''")[1].split("'''")[0]
R = []
def ok(name, cond, extra=''):
    R.append((name, bool(cond), extra)); print(('OK  ' if cond else 'ÉCHEC ') + name, extra)
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(viewport={'width': 1440, 'height': 900}, accept_downloads=True)
        await ctx.add_init_script(DIRMOCK + '\n(()=>{try{const p=JSON.parse(localStorage.getItem("etude.prefs")||"{}");p.tourDone=true;p.sbTab="pages";localStorage.setItem("etude.prefs",JSON.stringify(p));}catch(e){}})(); window.print = () => { window.__printed = (window.__printed||0) + 1; };')
        page = await ctx.new_page(); errs = []
        page.on('pageerror', lambda e: errs.append('PAGEERROR ' + str(e))); page.on('console', lambda m: errs.append(m.text) if m.type == 'error' else None)
        ev = page.evaluate
        # 0. Données créées avec l'ANCIENNE version
        await page.goto(OLD); await page.wait_for_timeout(900)
        await page.set_input_files('#fileInput', SYN); await page.wait_for_selector('.page canvas'); await page.wait_for_timeout(1200)
        await page.fill('#pageInput', '3'); await page.press('#pageInput', 'Enter'); await page.wait_for_timeout(500)
        await page.click('#quick'); await page.keyboard.type('Note créée avec l\'ancienne version'); await page.keyboard.press('Enter'); await page.wait_for_timeout(1200)
        oldn = await ev('window.__atelier.S.doc.notes.length')
        # 1. Nouvelle version : accueil et données retrouvées
        await page.goto(APP); await page.wait_for_timeout(1200)
        ok('accueil : « Reprendre un cours » visible', await ev('!document.getElementById("recents").classList.contains("hidden")'), await ev('document.getElementById("homeTitle").textContent'))
        ok('accueil : outils PDF masqués sans document', await ev('getComputedStyle(document.querySelector(".tb-center")).display === "none" && getComputedStyle(document.getElementById("modeSeg")).display === "none"'))
        await page.screenshot(path=f'{OUT}/01-accueil.png')
        await page.set_input_files('#fileInput', SYN); await page.wait_for_selector('.page canvas'); await page.wait_for_timeout(1500)
        ok('ouvrir un PDF', await ev('window.__atelier.S.pages.length') == 31)
        ok('ancienne note retrouvée (même stockage)', await ev('window.__atelier.S.doc.notes.some(n => n.title.includes("ancienne version") || n.html.includes("ancienne version"))'), f'notes={oldn}')
        ok('reprise à la page de l\'ancienne session', await ev('window.__atelier.S.current') == 3)
        # 2. Navigation
        await page.click('#nextBtn'); await page.wait_for_timeout(500); c1 = await ev('window.__atelier.S.current')
        await page.fill('#pageInput', '9'); await page.press('#pageInput', 'Enter'); await page.wait_for_timeout(1300); c2 = await ev('window.__atelier.S.current')
        await page.click('#viewer', position={'x': 30, 'y': 400}); await page.keyboard.press('ArrowRight'); await page.wait_for_timeout(500); c3 = await ev('window.__atelier.S.current')
        ok('changer de page (bouton, saisie, flèche)', (c1, c2, c3) == (4, 9, 10), str((c1, c2, c3)))
        z0 = await ev('window.__atelier.S.scale'); await page.click('#zoomIn'); await page.wait_for_timeout(300); z1 = await ev('window.__atelier.S.scale'); await page.click('#fitBtn'); await page.wait_for_timeout(300)
        ok('zoom + ajuster', z1 > z0)
        await page.click('#thumbsBtn'); await page.wait_for_timeout(500)
        ok('vignettes', await ev('!document.getElementById("thumbs").classList.contains("hidden")'))
        await page.click('#thumbsBtn')
        await page.fill('#searchInput', 'PISA'); await page.wait_for_timeout(1800)
        ok('recherche + flèches de résultats', await ev('document.getElementById("searchBox").classList.contains("searching") && getComputedStyle(document.getElementById("searchNext")).display !== "none"'), await ev('document.getElementById("searchInfo").textContent'))
        await page.fill('#searchInput', ''); await page.press('#searchInput', 'Escape')
        # 3. Notes : écrire et modifier
        await page.fill('#pageInput', '5'); await page.press('#pageInput', 'Enter'); await page.wait_for_timeout(600)
        await page.click('#quick'); await page.keyboard.type('Écart socio-économique : 111 → 92'); await page.keyboard.press('Enter'); await page.wait_for_timeout(300)
        await page.click('#addNote'); await page.keyboard.type('Six enseignements de PISA'); await page.keyboard.press('Enter'); await page.keyboard.type('Point 3 : dispositions défavorables.')
        await page.evaluate('''() => { const b=[...document.querySelectorAll('.note .body')].find(x=>x.textContent.includes('Point 3')); const r=document.createRange(); r.selectNodeContents(b); const s=getSelection(); s.removeAllRanges(); s.addRange(r); }''')
        await page.click('#fmt [data-cmd="bold"]'); await page.wait_for_timeout(200)
        await page.evaluate('() => { const s=getSelection(); s.collapseToEnd(); document.dispatchEvent(new Event("selectionchange")); }'); await page.wait_for_timeout(250)
        tagvis = await ev('(() => { const n=[...document.querySelectorAll(".note")].find(x=>x.textContent.includes("Point 3")); return getComputedStyle(n.querySelector(".note-tags")).display; })()')
        await page.click('.note:focus-within .note-tags .chip >> nth=0'); await page.wait_for_timeout(300)
        await page.screenshot(path=f'{OUT}/02-notes.png')
        h = await ev('window.__atelier.S.doc.notes.find(n=>n.title==="Six enseignements de PISA")')
        ok('écrire une note (titre, texte, gras, étiquette)', h and ('<b>' in h['html'] or 'bold' in h['html']) and len(h['tags']) == 1, f'tags visibles en édition : {tagvis}')
        await page.evaluate('''() => { const b=[...document.querySelectorAll('.note .body')].find(x=>x.textContent.includes('Point 3')); b.focus(); const r=document.createRange(); r.selectNodeContents(b); r.collapse(false); const s=getSelection(); s.removeAllRanges(); s.addRange(r); }''')
        await page.keyboard.type(' Modifiée.'); await page.wait_for_timeout(900)
        ok('modifier une note', 'Modifiée' in (await ev('window.__atelier.S.doc.notes.find(n=>n.title==="Six enseignements de PISA").html')))
        await page.click('[data-dd="ddTpl"]'); await page.click('#ddTpl [data-tpl="cornell"]'); await page.wait_for_timeout(300)
        ok('modèle Cornell', await ev('window.__atelier.S.doc.notes.some(n=>n.html.includes("cornell"))'))
        await page.click('#ddStyle >> xpath=..', timeout=1000) if False else None
        # 4. Annoter
        await page.click('#annotBtn'); await page.wait_for_timeout(300)
        await page.screenshot(path=f'{OUT}/03-menu-annoter.png')
        await page.click('#pinBtn'); await page.wait_for_timeout(300)
        lbl = await ev('document.getElementById("annotLbl").textContent'); ban = await ev('!!document.querySelector(".mode-banner")')
        await page.screenshot(path=f'{OUT}/04-epingler.png')
        r = await ev('(() => { const b=document.querySelector(".page[data-n=\\"5\\"]").getBoundingClientRect(); return {x:b.left+200, y:Math.max(b.top,120)+150}; })()')
        await page.mouse.click(r['x'], r['y']); await page.wait_for_timeout(600)
        ok('annoter : épingler (bouton actif + bandeau + épingle posée)', lbl == 'Épingler' and ban and await ev('window.__atelier.S.doc.notes.some(n=>n.pin)'), lbl)
        ok('annoter : bouton revient à « Annoter »', await ev('document.getElementById("annotLbl").textContent') == 'Annoter')
        await page.keyboard.press('Escape')
        await page.click('#annotBtn'); await page.click('#drawBtn'); await page.wait_for_timeout(300)
        r = await ev('(() => { const b=document.querySelector(".page[data-n=\\"5\\"]").getBoundingClientRect(); return {x:b.left+150, y:Math.max(b.top,120)+300}; })()')
        await page.mouse.move(r['x'], r['y']); await page.mouse.down(); await page.mouse.move(r['x']+120, r['y']+30, steps=8); await page.mouse.up(); await page.wait_for_timeout(300)
        await page.screenshot(path=f'{OUT}/05-dessin.png')
        await page.click('.drawbar [data-a="done"]'); await page.wait_for_timeout(300)
        ok('annoter : dessiner', await ev('(window.__atelier.S.doc.ink||[]).length') >= 1)
        await page.keyboard.press('Alt+KeyA'); await page.wait_for_timeout(200)
        ok('raccourci ⌥A (associer)', await ev('window.__atelier.S.mode') == 'link' and await ev('document.getElementById("annotBtn").classList.contains("on")'))
        await page.keyboard.press('Escape')
        await page.evaluate('() => { const sp=[...document.querySelectorAll(".page[data-n=\\"5\\"] .textLayer span")].find(s=>s.textContent.trim().length>25); sp.scrollIntoView({block:"center"}); const r=document.createRange(); r.selectNodeContents(sp); const s=getSelection(); s.removeAllRanges(); s.addRange(r); document.getElementById("viewer").dispatchEvent(new MouseEvent("mouseup",{bubbles:true})); }'); await page.wait_for_timeout(300)
        await page.click('.bubble [data-h="yellow"]'); await page.wait_for_timeout(300)
        ok('surligner une sélection', await ev('window.__atelier.S.doc.highlights.length') >= 1)
        # 5. Modes
        pg = await ev('window.__atelier.S.current'); nn = await ev('window.__atelier.S.doc.notes.length')
        await page.click('#modeSeg [data-mode="revise"]'); await page.wait_for_timeout(400)
        st = await ev('({rev: document.body.classList.contains("mode-revise"), fmt: getComputedStyle(document.getElementById("fmt")).display, bar: getComputedStyle(document.getElementById("revbar")).display, mask: document.getElementById("revision").checked, hidden: document.querySelectorAll(".revision .note:not(.shown) .reveal").length})')
        await page.screenshot(path=f'{OUT}/06-reviser.png')
        ok('mode Réviser (fiches, masquage, progression regroupés)', st['rev'] and st['fmt'] == 'none' and st['bar'] == 'flex' and st['mask'], json.dumps(st))
        await page.click('#revMenuBtn'); await page.click('#cardsBtn'); await page.wait_for_timeout(500); fc = await ev('!!document.querySelector(".fc-wrap, .modal")'); await page.keyboard.press('Escape'); await page.wait_for_timeout(200)
        await page.click('#progBtn'); await page.wait_for_timeout(400); pr = await ev('!!document.querySelector(".modal")'); await page.keyboard.press('Escape')
        ok('Fiches et Progression s\'ouvrent', fc and pr)
        await page.click('#modeSeg [data-mode="notes"]'); await page.wait_for_timeout(400)
        ok('retour à « Prendre des notes » : même page, mêmes notes, réponses visibles', await ev('window.__atelier.S.current') == pg and await ev('window.__atelier.S.doc.notes.length') == nn and not await ev('document.getElementById("revision").checked'))
        await page.keyboard.press('Alt+KeyR'); await page.wait_for_timeout(300)
        ok('raccourci ⌥R → mode Réviser', await ev('document.body.classList.contains("mode-revise")'))
        await page.click('#modeSeg [data-mode="notes"]'); await page.wait_for_timeout(200)
        await page.keyboard.press('Alt+KeyN'); await page.wait_for_timeout(300)
        ok('raccourci ⌥N', await ev('window.__atelier.S.doc.notes.length') == nn + 1)
        await page.keyboard.press('Escape'); await page.click('#viewer', position={'x': 30, 'y': 400})
        # 6. Sauvegarder
        await page.click('#saveBtn'); await page.wait_for_timeout(400); await page.click('[data-b="dir"]'); await page.wait_for_timeout(1500)
        files = await ev('Object.keys(window.__files)')
        ok('sauvegarde dans un dossier + historique', any('mes notes.json' in f for f in files) and any('Historique' in f for f in files), str(files))
        await page.keyboard.press('Meta+s'); await page.wait_for_timeout(500)
        await page.click('#coursBtn'); await page.wait_for_timeout(200); await page.click('#ddCours [data-c="backup"]'); await page.wait_for_timeout(400)
        ok('menu Cours → Sauvegarde et historique', await ev('!!document.querySelector(".hist-row") || (document.querySelector(".modal-h h3")||{}).textContent?.includes("Sauvegarde")'))
        await page.keyboard.press('Escape')
        # 7. Exporter
        async with page.expect_download() as d:
            await page.click('#expBtn'); await page.click('#ddExport [data-x="md"]')
        dl = await d.value; md = open(await dl.path(), encoding='utf-8').read()
        ok('exporter .md', 'Six enseignements' in md, dl.suggested_filename)
        await page.click('#expBtn'); await page.click('#ddExport [data-x="notes"]'); await page.click('#npGo'); await page.wait_for_timeout(900)
        ok('exporter « Mes notes en PDF » (impression)', await ev('window.__printed||0') >= 1)
        async with page.expect_download() as d:
            await page.click('#coursBtn'); await page.click('#ddCours [data-x="json"]')
        dl = await d.value; bj = json.load(open(await dl.path(), encoding='utf-8'))
        ok('télécharger une sauvegarde complète (.json)', 'docs' in json.dumps(bj)[:5000] or isinstance(bj, dict), dl.suggested_filename)
        await page.click('#expBtn'); await page.click('#ddExport [data-x="annot"]'); await page.wait_for_timeout(2500)
        await page.keyboard.press('Escape')
        # 8. Affichage
        await page.click('#viewBtn'); await page.click('#segTheme [data-v="dark"]'); await page.wait_for_timeout(300); await page.keyboard.press('Escape')
        ok('thème sombre', await ev('document.documentElement.dataset.theme') == 'dark')
        await page.mouse.move(700, 600); await page.wait_for_timeout(300)
        await page.screenshot(path=f'{OUT}/07-sombre.png')
        await page.click('#viewBtn'); await page.wait_for_timeout(300); await page.screenshot(path=f'{OUT}/08-menu-affichage.png')
        await page.click('#segTheme [data-v="light"]'); await page.keyboard.press('Escape')
        await page.keyboard.press('Alt+KeyL'); await page.wait_for_timeout(600)
        ok('lecture plein écran ⌥L', await ev('document.body.classList.contains("reading")')); await page.keyboard.press('Escape'); await page.wait_for_timeout(300)
        # 9. Recharger
        await page.wait_for_timeout(1000)
        before = await ev('window.__atelier.S.doc.notes.length')
        await page.reload(); await page.wait_for_timeout(1500)
        await page.screenshot(path=f'{OUT}/09-accueil-recents.png')
        await page.set_input_files('#fileInput', SYN); await page.wait_for_selector('.page canvas'); await page.wait_for_timeout(1500)
        ok('recharger : notes, surlignage, dessin conservés', await ev('window.__atelier.S.doc.notes.length') == before and await ev('window.__atelier.S.doc.highlights.length') >= 1 and await ev('(window.__atelier.S.doc.ink||[]).length') >= 1, f'{before} notes')
        # 10. Largeurs d'écran
        for w in (1440, 1280, 1100):
            await page.set_viewport_size({'width': w, 'height': 820}); await page.wait_for_timeout(500)
            ov = await ev('(() => { const t=document.querySelector(".topbar"); const r=[...t.querySelectorAll("button, input")].filter(x=>x.offsetParent).map(x=>x.getBoundingClientRect().right); return {sw: t.scrollWidth, cw: t.clientWidth, maxRight: Math.round(Math.max(...r)), doc: document.documentElement.scrollWidth}; })()')
            ok(f'{w} px : barre sans débordement', ov['sw'] <= ov['cw'] and ov['maxRight'] <= w and ov['doc'] <= w, json.dumps(ov))
            await page.screenshot(path=f'{OUT}/10-largeur-{w}.png')
        ok('aucune erreur JavaScript', not errs, str(errs[:5]))
        print('\nRÉSUMÉ', sum(1 for r in R if r[1]), '/', len(R))
        await b.close()
asyncio.run(main())
